log-level = "INFO"
measure-speed = true

#############################

[profiler]
activated = true
profile-function = true
time-function = false
output-file = "profiler.txt"

#############################

[autobahn]
port = 4222

#############################

[image-recognition]
image-input-topic = "recognition/image_input"
image-output-topic = "recognition/image_output"
model = "yolov5mu.pt"
device = "mps"

[image-recognition.trainer]
name = "yolov8_custom"
imgsz = 640
epochs = 10
data-yaml-path = "data.yaml"
dataset-root-path = "dataset"
batch-size = 16

#############################

[april-detection]
cameras = ["left"]
tag-size = 0.20
family = "tag36h11"
nthreads = 4
quad_decimate = 2.0
quad_sigma = 0.0
refine_edges = 1
decode_sharpening = 0.25
searchpath = ["apriltags"]
debug = 0

[april-detection.message]
post-camera-input-topic = "apriltag/camera"
post-camera-output-topic = "apriltag/tag"

[april-detection.left]
focal-length-x = 950
focal-length-y = 950
center-x = 640
center-y = 360
name = "left"

#############################


[camera-parameters]
cameras = ["left"]

[camera-parameters.left]
dist-coeff = [
    -0.3699966980628528,
    0.1821265728482258,
    -0.000017146753545554133,
    0.001312177635207973,
    0.060869889777672416,
]
camera-matrix = [
    [
        1457.5931734170763,
        0.0,
        997.1660947238562,
    ],
    [
        0.0,
        1401.1036215895347,
        539.0780233970917,
    ],
    [
        0.0,
        0.0,
        1.0,
    ],
]
