FROM ubuntu:24.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    systemd \
    systemd-sysv \
    sudo \
    git \
    make \
    ca-certificates \
    build-essential \
    python3 \
    python3-dev \
    python3-pip \
    python3-venv \
    protobuf-compiler \
    thrift-compiler \
    && rm -rf /var/lib/apt/lists/*

COPY scripts/setup.sh /setup.sh
COPY . /opt/blitz/B.L.I.T.Z/

RUN chmod +x /setup.sh

ENV TARGET_NAME="test"
ENV TARGET_FOLDER="/opt/blitz/"
ENV SERVICE_NAME="blitz-service"
ENV DEV_LOCAL_OVERRIDE="true"
RUN bash /setup.sh

CMD ["/sbin/init"]
