FROM ubuntu:24.04

RUN apt-get update && DEBIAN_FRONTEND=noninteractive apt-get install -y \
    systemd \
    systemd-sysv \
    sudo \
    git \
    make \
    ca-certificates \
    build-essential \
    python3 \
    python3-dev \
    python3-pip \
    python3-venv \
    rsync \
    unzip \
    protobuf-compiler \
    thrift-compiler \
    curl \
    nano \
    && rm -rf /var/lib/apt/lists/*

CMD ["/sbin/init"]
