# ------------- POS EXTRAPOLATOR -------------

[pos-extrapolator]
cameras-to-analyze = ["left"]
tag-confidence-threshold = 0.5
position-extrapolation-method = "average-position"

[pos-extrapolator.tag-position-config]
tag-position-config-file = "tag_pos/tag_position_config.json"
config-in-use = "1"                                           # TODO

[pos-extrapolator.message]
post-tag-input-topic = "apriltag/tag"
post-robot-position-output-topic = "pos-extrapolator/robot-position"

# ------------- KALMAN FILTER -------------

[kalman-filter]
state-vector = [0.0, 0.0, 0.0, 0.0, 0.0] # [x, y, vx, vy, theta]
time-step = 0.1
state-transition-matrix = [
    [1.0, 0.0, 0.1, 0.0, 0.0], # no format
    [0.0, 1.0, 0.0, 0.1, 0.0], # no format
    [0.0, 0.0, 1.0, 0.0, 0.0], # no format
    [0.0, 0.0, 0.0, 1.0, 0.0], # no format
    [0.0, 0.0, 0.0, 0.0, 1.0], # no format
]
uncertainty-matrix = [
    [500.0, 0.0, 0.0, 0.0, 0.0], # no format
    [0.0, 500.0, 0.0, 0.0, 0.0], # no format
    [0.0, 0.0, 500.0, 0.0, 0.0], # no format
    [0.0, 0.0, 0.0, 500.0, 0.0], # no format
    [0.0, 0.0, 0.0, 0.0, 500.0], # no format
]
process-noise-matrix = [
    [0.1, 0.0, 0.0, 0.0, 0.0], # no format
    [0.0, 0.1, 0.0, 0.0, 0.0], # no format
    [0.0, 0.0, 0.1, 0.0, 0.0], # no format
    [0.0, 0.0, 0.0, 0.1, 0.0], # no format
    [0.0, 0.0, 0.0, 0.0, 0.1], # no format
]
dim-x-z = [5, 5]
sensors = ["april-tag", "odometry"]

# ---

[kalman-filter.april-tag]
measurement-noise-matrix = [
    [1.0, 0.0, 0.0, 0.0, 0.0], # no format
    [0.0, 1.0, 0.0, 0.0, 0.0], # no format
    [0.0, 0.0, 1.0, 0.0, 0.0], # no format
    [0.0, 0.0, 0.0, 1.0, 0.0], # no format
    [0.0, 0.0, 0.0, 0.0, 1.0], # no format
]
measurement-conversion-matrix = [
    [1.0, 0.0, 0.0, 0.0, 0.0], # no format
    [0.0, 1.0, 0.0, 0.0, 0.0], # no format
    [0.0, 0.0, 1.0, 0.0, 0.0], # no format
    [0.0, 0.0, 0.0, 1.0, 0.0], # no format
    [0.0, 0.0, 0.0, 0.0, 1.0], # no format
]

# ---

[kalman-filter.odometry]
measurement-noise-matrix = [
    [0.5, 0.0, 0.0, 0.0, 0.0], # no format
    [0.0, 0.5, 0.0, 0.0, 0.0], # no format
    [0.0, 0.0, 0.5, 0.0, 0.0], # no format
    [0.0, 0.0, 0.0, 0.5, 0.0], # no format
    [0.0, 0.0, 0.0, 0.0, 0.5], # no format
]
measurement-conversion-matrix = [
    [1.0, 0.0, 0.0, 0.0, 0.0], # no format
    [0.0, 1.0, 0.0, 0.0, 0.0], # no format
    [0.0, 0.0, 1.0, 0.0, 0.0], # no format
    [0.0, 0.0, 0.0, 1.0, 0.0], # no format
    [0.0, 0.0, 0.0, 0.0, 1.0], # no format
]

# ------------- CAMERA PARAMETERS -------------

[camera-parameters]
cameras = ["left"]

[camera-parameters.left]
port = 0
rotation-vector = [0.0, 0.0] # [pitch, yaw]
translation-vector = [0.0, 0.0, 0.0]
dist-coeff = [
    -0.43237149459673446,
    0.19572749208462567,
    0.0006948679465891381,
    5.132481888695187e-5,
    -0.05070219401624212,
]
camera-matrix = [
    [
        1459.013092168164,
        0.0,
        941.1817368129706,
    ],
    [
        0.0,
        1450.9546373771313,
        523.0240888523196,
    ],
    [
        0.0,
        0.0,
        1.0,
    ],
]
