# main_config_path="test/config.toml" # that is a main config file with ALL the configs. The python will look for this param and if it is defined, it will try to access the main config file.
# However, if the main config file is not there, the python will just default to acessing this config file.

# The requirements and the meanings of each entry are in the README file.

log-level = "DEBUG"
measure-speed = false

[autobahn]
port = 8080

[april-detection]
cameras = ["left"]
tag-size = 0.20
family = "tag36h11"
nthreads = 4
quad_decimate = 2.0
quad_sigma = 0.0
refine_edges = 1
decode_sharpening = 0.25
searchpath = ["apriltags"]
debug = 0

[april-detection.message]
post-camera-input-topic = "apriltag/camera"
post-camera-output-topic = "apriltag/tag"

[april-detection.left]
focal-length-x = 1459.013092168164
focal-length-y = 1450.9546373771313
center-x = 941.1817368129706
center-y = 523.0240888523196
name = "left"
